#!/bin/sh
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NOCOLOR='\033[0m'

echo ""
echo -e "${YELLOW}Building project...${NOCOLOR}"
    
DOTNET_CLI_TELEMETRY_OPTOUT=1
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

dotnet build RegisterApi --verbosity minimal
dotnet build Tests/Integration --verbosity minimal

if [ $? -ne 0 ] ; then
    echo ""
	echo -e "${RED}The build failed. Please fix the problems before pushing the changes${NOCOLOR}"
	echo ""
	exit 1
fi

echo ""
echo -e "${YELLOW}Executing Integration Tests ...${NOCOLOR}"
echo ""

dotnet test Tests/Integration --verbosity minimal

if [ $? -ne 0 ] ; then
    echo ""
	echo -e "${RED}One or more integration tests failed. Please fix the problems before pushing the changes${NOCOLOR}"
	echo ""
	exit 1
fi

echo ""
echo -e "${GREEN}Everything is ok!${NOCOLOR}"
echo ""

exit 0