name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Push image
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./RegisterAPI/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/register-api:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/register-api:latest